# permissions for end users to edit sparkhistoryservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sparkhistoryserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spark-k8s-operator
    app.kubernetes.io/part-of: spark-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: sparkhistoryserver-editor-role
rules:
- apiGroups:
  - spark.zncdata.dev
  resources:
  - sparkhistoryservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spark.zncdata.dev
  resources:
  - sparkhistoryservers/status
  verbs:
  - get
